// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsCypkHBCW4agBDTOst3cLj_lRIjx8Jtg',
    appId: '1:720877713532:web:6b2be11415ff34f89e71f9',
    messagingSenderId: '720877713532',
    projectId: 'my-app-flut',
    authDomain: 'my-app-flut.firebaseapp.com',
    storageBucket: 'my-app-flut.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf8xkj3Jb4igM1GkdYroLYaXr8skAF5qQ',
    appId: '1:720877713532:android:0836be0d536cceab9e71f9',
    messagingSenderId: '720877713532',
    projectId: 'my-app-flut',
    storageBucket: 'my-app-flut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdV_r7ncpIWB2HDY_1nPi_mpZvD6RrPA',
    appId: '1:720877713532:ios:b1ce3f572d8c311f9e71f9',
    messagingSenderId: '720877713532',
    projectId: 'my-app-flut',
    storageBucket: 'my-app-flut.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdV_r7ncpIWB2HDY_1nPi_mpZvD6RrPA',
    appId: '1:720877713532:ios:b1ce3f572d8c311f9e71f9',
    messagingSenderId: '720877713532',
    projectId: 'my-app-flut',
    storageBucket: 'my-app-flut.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsCypkHBCW4agBDTOst3cLj_lRIjx8Jtg',
    appId: '1:720877713532:web:efffbe4e29ffc62e9e71f9',
    messagingSenderId: '720877713532',
    projectId: 'my-app-flut',
    authDomain: 'my-app-flut.firebaseapp.com',
    storageBucket: 'my-app-flut.firebasestorage.app',
  );
}
