import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'views/authWrapper.dart';
import 'package:firebase_auth/firebase_auth.dart';
import "services/practice.dart";
import "services/practice1.dart";

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  try {
    debugPrint("FirebaseAuth instance => ${FirebaseAuth.instance}");
  } catch (e) {
    print(e);
  }
  runApp(AkshayApp());
}

class AkshayApp extends StatelessWidget {
  const AkshayApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My First App',
      theme: ThemeData(colorScheme: .fromSeed(seedColor: Colors.deepPurple)),
      // home: const Authwrapper(),
      home: Authwrapper(),
    );
  }
}
